import '../styles/global.css'; // Import global styles here

export const metadata = {
  title: 'finchat-replication.js',
  description: 'Generated by Next.js ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
